name: bookly_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  awesome_snackbar_content: ^0.1.5
  awesome_snackbar_content_new: ^0.1.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.7
  fancy_snackbar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.6.2
  google_fonts: ^4.0.0
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
